name: CI/CD

on: push

env:
  ADMIN_ID: 222594823

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.6'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r tests/requirements.txt
      - name: Test with pytest
        env:
          DADATA_TOKEN: ${{ secrets.DADATA_TOKEN }}
          DADATA_SECRET: ${{ secrets.DADATA_SECRET }}
        run: |
          python -m pytest tests

  deploy:
    name: Deploy to Yandex Cloud
    runs-on: ubuntu-latest
    needs: test
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Cloud Function
        uses: goodsmileduck/yandex-serverless-action@v1
        with:
          token: ${{ secrets.OAUTH_TOKEN }}
          function_id: 'd4eot9caq0j29va7i2b4'
          runtime: 'python37'
          memory: '128'
          entrypoint: 'main.handler'
          environment:
            "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }},\
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }},\
            BOT_TOKEN=${{ secrets.BOT_TOKEN }},\
            admin_id=${{ env.ADMIN_ID }},\
            DADATA_TOKEN=${{ secrets.DADATA_TOKEN }},\
            DADATA_SECRET=${{ secrets.DADATA_SECRET }}"
          source: '.'
          exclude: 'README.md,scripts,.git,.github'
